// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaRBGhucIMXWdseawKRm0sqxrGmySfvGY',
    appId: '1:872254798289:web:4e95e3435caa4e588608f0',
    messagingSenderId: '872254798289',
    projectId: 'srocks-636d5',
    authDomain: 'srocks-636d5.firebaseapp.com',
    storageBucket: 'srocks-636d5.firebasestorage.app',
    measurementId: 'G-3B5BB38QY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItcVFppU2VWeJwKziSV3ZyXfs4BlZY3Q',
    appId: '1:872254798289:android:a3fd8dc854790c3d8608f0',
    messagingSenderId: '872254798289',
    projectId: 'srocks-636d5',
    storageBucket: 'srocks-636d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3VHYyqGADGlVRyKa6PQUjvyD_vQG8B_U',
    appId: '1:872254798289:ios:d9d5d454e08f02f88608f0',
    messagingSenderId: '872254798289',
    projectId: 'srocks-636d5',
    storageBucket: 'srocks-636d5.firebasestorage.app',
    iosBundleId: 'com.example.sRocks',
  );
}
